### ISSUE TITLE
Transmitted Phase for S-Pol has 90deg shift in 0.3.3

### ISSUE THREAD

**Issue by knobold** [alexysong/inkstone#5]
Hi,
I've run into a strange issue when updating from inkstone 0.2.18 to 0.3.3. I'm using the attributes (self.ao,self.bi) to calculate the transmitted phase difference for TE- and TM-waves incident on a 1D grating. I added a modified version of _calc_bi_ao(self) to do this: 

>def Get_bi_ao(sim_object):        
>    #get the reflected amplitude bi and transmitted amplitude ao    
>    sim_object.solve()
>    ai_v = sim_object.pr.ai.reshape((2 * sim_object.pr.num_g, 1))
>    bo_v = sim_object.pr.bo.reshape((2 * sim_object.pr.num_g, 1))
>    sm11 = sim_object.sm[0]
>    sm12 = sim_object.sm[1]
>    sm21 = sim_object.sm[2]
>    sm22 = sim_object.sm[3]
>    bi = sm11 @ ai_v + sm12 @ bo_v
>    ao = sm21 @ ai_v + sm22 @ bo_v
>    #ravel 2d array (just one column) to 1d array
>    bi = bi.ravel()
>    ao = ao.ravel()    
>    return bi,ao

With np.angle(ao[0]) I then get the 0th-order phase for p-polarization and with np.angle(ao[num_g]) for s-pol.  This doesn't give the desired results in 0.3.3 and Ive noticed that for the elements of self.ao corresponding to s-pol [index num_g to 2*num_g-1] the real and imaginary parts are exchanged which results in a phase shift of 90° for s-pol. The values corresponding to p-pol are still exactly the same. Is this phase shift of +90° for s-pol desired? I can simply subtract the difference but I don't unterstand where this change came from.

Output of Get_bi_ao() in version 0.2.18:
[ 1.17456367-0.12200208j -0.06660174+1.19661283j]
Output of Get_bi_ao() in version 0.3.3:
[ 1.17456367-0.12200208j 1.19661283+0.06660174j]

Attached Im posting my script that reproduces this issue.

[grating_1D_phase.txt](https://github.com/alexysong/inkstone/files/12899654/grating_1D_phase.txt)

Best regards,
Tim

**Comment by alexysong** [comment]
Hi Tim,

Thanks for using Inkstone. 

* I think from what you are describing, the `GetAmplitudesByOrder()` is the native API that gives the complex amplitudes of the forward and backward waves any any $z$ in any layer.
* The observed change could be due to a change of the choice of layer eigen during recent updates for stability in extreme situations.
* I couldn't run the example code you gave as there are some problems installing `seaborn` and `pandas`. Could you send one without those dependencies?
* Can you update to the newest 3da978543c415437e126254fe77463279f9b9aee (available in PyPI) and try again?

Best,
Alex

**Comment by knobold** [comment]
Hi Alex, 
Thank you for your response. 
Using the native API solved the problem. So this issue can be closed. Much better to do it like this and be able to specify the z coordinate as well, thank you!
When updating to 0.3.10 however I get a new error related to AddLayerCopy(). When adding Layer copies this warning is now triggered:
>warn('You might have called something that is not defined in a copy layer: "{:s}". Instead you should call it from the original layer: "{:s}". Nothing is changed.'.format(self.name, self.original_layer_name))

with the error message pointing to *self.imfl in a call of s_1l_rsp() being a NoneType object. 
This error doesnt happen in version 0.3.3 and lower and is reproducible for different structures.  
Below I've added the updated script with the seaborn and pandas dependencies removed. 
[1dgrating.txt](https://github.com/alexysong/inkstone/files/13249507/1dgrating.txt)

**Comment by alexysong** [comment]
Thanks for the feedback. The new bug is fixed in 20d90c8f7c20ed5fb3e9743cea797330d169def6.
Enjoy!

**Comment by alexysong** [comment]
Actually, please upgrade to 620708845269a8035db505ca28022335bdeebcfe. There was a bug causing $s$-polarization to be incorrect for uniform layers.
