### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by fatpunkybearass** [alexysong/inkstone#6]
Hi thanks for the inkstone package.

I'd like to ask about questions other than issues. 

1. What is the num_g parameter? Why the higher this value the smaller z distance I can calculate? 
for num_g=5 
![image](https://github.com/alexysong/inkstone/assets/93345787/e95152be-5272-4a3f-9a3e-5fbe4f14b798)
for num_g=50
![image](https://github.com/alexysong/inkstone/assets/93345787/f55c74ef-b4fd-4658-a5e6-7a56eedc6a10)

3. And I set up a basic grating and use normal incidence (s.SetExcitation(theta=0., phi=0., s_amplitude=1, p_amplitude=0)) , is the field in x-z plane something I can see in real experiment using just laser and grating, nothing else?  I did real experiment using laser to shine on this grating and I got diffracted plane waves into different directions, but here in simulation in the x-z plane E-field I see beams propagating parallel forward.
simulation
![image](https://github.com/alexysong/inkstone/assets/93345787/21ce9482-1e5b-49ed-a62a-942310b04c35)
experiment
![image](https://github.com/alexysong/inkstone/assets/93345787/6e845df6-b421-490e-b192-2d7ea9f8e79a)

Thank you very much

**Comment by alexysong** [comment]
I am going to mark this as closed for now due to inactivity. Please feel free to comment/reply.
